# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site and can be found in the .env file.
# If you look in the HTML files, you will see them accessed via {{ site.env.TITLE }}, 
# {{ site.env.EMAIL }}, and so on. You can create any custom variable you would like,
# and they will be accessible in the templates via {{ site.env.MYVARIABLE }}.
#
# Build settings
plugins:
  - jekyll-dotenv

image_processing:
  large:
    source: photos/original
    destination: photos/large
    resize_to_limit: [2048, 2048]
    saver:
      strip: true
  thumbnail:
    source: photos/original
    destination: photos/thumbnail
    resize_to_limit: [640, 640]
    saver:
      strip: true
  tint:
    source: photos/original
    destination: photos/tint
    resize_to_fill: [1,1]
    saver:
      strip: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [Dockerfile, LICENSE, docker-compose.yml, README.md, Procfile]
